data:
  root_dir: "/netscratch/herzig/datasets/BabyCry_no_augment"
  data_type: "mel-spectogram"
  augmentation: False

model:
  architecture: "jdc"
  pretrained: "src/models/jdc/bst.t7"
  num_classes: 1
  seq_len: 192
  bilstm:
    hidden_size: 64
    num_layers: 2
    dropout: 0.0

batch_size: 16
num_workers: 8
num_epochs: 20
lr: 0.00005
dropout: 0.0
