data:
  root_dir: "/netscratch/herzig/datasets/BabyCry_augment_1"
  version: 1
  data_type: "mel-spectogram"
  augmentation: False

model:
  architecture: "jdc"
  pretrained: "src/models/jdc/bst.t7"
  num_classes: 1
  seq_len: 192
  bilstm:
    hidden_size: 128
    num_layers: 8
    dropout: 0.2

batch_size: 256
num_workers: 8
num_epochs: 30
lr: 0.01
