data:
  root_dir: ""
  version: 1
  data_type: "mel-spectogram"
  augmentation: False

model:
  architecture: "jdc"
  pretrained: "src/models/jdc/bst.t7"
  num_classes: 2


batch_size: 8
num_workers: 8
num_epochs: 2
lr: 0.001
