mode: 'train'
logger: 'wandb'

model:
  name: 'trill1'
  pretrained: 'models/torch_models/trill1.pth'
  num_classes: 2
  bilstm: True

data:
  dataset: 'baby_cry'

train_args:
  batch_size: 32
  lr: 0.0001
  log_every_n_steps: 10

wandb:
  project: 'baby_cry'
  offline: False